spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 192.168.115.128:27001
        - 192.168.115.128:27002
        - 192.168.115.128:27003
    password: 696903
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
